name: Notify central docs of update
# todo figure out the DOCS_DEPLOY_TOKEN

on:
  push:
    paths:
      - 'docs/**'

jobs:
  notify-docs-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs site rebuild
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DOCS_DEPLOY_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/your-org/central-docs-repo/actions/workflows/build-docs.yml/dispatches \
            -d '{"ref":"main"}'
